### ISSUE TITLE
PBC on windows

### ISSUE THREAD

**Issue by alaneuler** [blynn/pbc#6]
Hello,
       I am using PBC binary distribution in Visual Studio. And I change the code as http://stackoverflow.com/questions/25446726/running-pbc-in-windows-visual-studio Jason said. But I get the link warning pbc.lib(d000345.o) : warning LNK4078:multiple 'section name' sections found with different attributes. Is this alright? But when I test on pairing type d159, my runing time is over 100ms, totally different from PBC mannul benchmark.
      And I use GMP binary distribution.
      Can you help me? Thanks in advance!

**Comment by WinPack** [comment]
About the timing issue I don't know, but the error of multiple sections is "normal" (it appears to me also). BTW, I am Jason (the post owner).
